// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBntE51WQBp80b2YEW5vwYdUj6vdx6C0as',
    appId: '1:977182788854:web:f1004509e15a0c0c1730d7',
    messagingSenderId: '977182788854',
    projectId: 'to-do-list-4f1cc',
    authDomain: 'to-do-list-4f1cc.firebaseapp.com',
    storageBucket: 'to-do-list-4f1cc.appspot.com',
    measurementId: 'G-97XKF31YQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_MbRPawEWRuYB_gnOWphDHDlqHexSZdw',
    appId: '1:977182788854:android:8a175dd0e18a44411730d7',
    messagingSenderId: '977182788854',
    projectId: 'to-do-list-4f1cc',
    storageBucket: 'to-do-list-4f1cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNZ24j_aRsCELKwJJAxOdugvEciwptUTw',
    appId: '1:977182788854:ios:4f7529b65f8d27261730d7',
    messagingSenderId: '977182788854',
    projectId: 'to-do-list-4f1cc',
    storageBucket: 'to-do-list-4f1cc.appspot.com',
    iosBundleId: 'com.example.tugasFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNZ24j_aRsCELKwJJAxOdugvEciwptUTw',
    appId: '1:977182788854:ios:52b1e783c5973dff1730d7',
    messagingSenderId: '977182788854',
    projectId: 'to-do-list-4f1cc',
    storageBucket: 'to-do-list-4f1cc.appspot.com',
    iosBundleId: 'com.example.tugasFirebase.RunnerTests',
  );
}
